import {
  Activity,
  BarChart3,
  Bot,
  Boxes,
  CalendarDays,
  ClipboardCheck,
  FileBarChart,
  GitBranch,
  HeartPulse,
  ListChecks,
  MessageSquare,
  PackageSearch,
  Route,
  ShieldCheck,
  Stethoscope,
  UserCog,
  Users,
  WandSparkles,
  Workflow,
} from "lucide-react";

import type { AdminNavItem } from "@/components/layout/admin-shell";

export const pathwayNavItems: AdminNavItem[] = [
  { label: "Dashboard", icon: BarChart3, section: "main", href: "/dashboard" },
  {
    label: "Root Pathways",
    icon: GitBranch,
    section: "wellness",
    href: "/root-pathways/glp-1-support",
    active: true,
  },
  { label: "Pathway Library", icon: HeartPulse, section: "wellness" },
  { label: "Plans & Protocols", icon: ClipboardCheck, section: "wellness" },
  { label: "Products", icon: Boxes, section: "wellness" },
  { label: "Ingredients", icon: PackageSearch, section: "wellness", href: "/ingredients-intelligence" },
  { label: "Interactions", icon: Activity, section: "wellness" },
  { label: "Rules Engine", icon: ClipboardCheck, section: "wellness" },
  { label: "Users", icon: Users, section: "engagement", href: "/users" },
  { label: "Journeys", icon: GitBranch, section: "engagement" },
  { label: "Assessments", icon: ListChecks, section: "engagement" },
  { label: "Follow Ups", icon: CalendarDays, section: "engagement" },
  { label: "Communications", icon: MessageSquare, section: "engagement", href: "/conversations" },
  { label: "Analytics", icon: BarChart3, section: "intelligence" },
  {
    label: "AI Optimization Center",
    icon: Bot,
    section: "intelligence",
    href: "/ai-optimization-center",
  },
  { label: "Prompt System", icon: WandSparkles, section: "intelligence", href: "/prompt-system" },
  { label: "Reports", icon: FileBarChart, section: "intelligence" },
  {
    label: "Advanced Journey Builder",
    icon: Workflow,
    section: "orchestration",
    href: "/journey-builder",
  },
  {
    label: "Live User Journey",
    icon: Route,
    section: "orchestration",
    href: "/live-user-journey",
  },
  { label: "Physicians", icon: Stethoscope, section: "admin" },
  { label: "Administrators", icon: UserCog, section: "admin" },
  { label: "Settings", icon: ShieldCheck, section: "admin" },
];

export const pathwayTabs = [
  "Overview",
  "Funnel Flow",
  "Education",
  "Quick Actions",
  "Plans & Protocols",
  "Ingredients",
  "Optimization Rules",
  "AI Instructions",
  "Personalization",
  "Follow-Up Timeline",
  "Analytics",
  "Self Learning",
  "Physician Review",
  "Activity Logs",
];
